In [1]:
import numpy as np
my_list = [1,2,3]
type(my_list)

In [3]:
type(np.array(my_list))

numpy.ndarray

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [7]:
np.arange(0,10,2) #start,stop,step
                  #SHIFT + TAB 

array([0, 2, 4, 6, 8])

In [12]:
np.zeros((3,3)) # single value is array, or tuple for matrix 

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [13]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [14]:
np.linspace(10,100,30)

array([  10.        ,   13.10344828,   16.20689655,   19.31034483,
         22.4137931 ,   25.51724138,   28.62068966,   31.72413793,
         34.82758621,   37.93103448,   41.03448276,   44.13793103,
         47.24137931,   50.34482759,   53.44827586,   56.55172414,
         59.65517241,   62.75862069,   65.86206897,   68.96551724,
         72.06896552,   75.17241379,   78.27586207,   81.37931034,
         84.48275862,   87.5862069 ,   90.68965517,   93.79310345,
         96.89655172,  100.        ])

In [15]:
np.random.randint(0,100)

11

In [16]:
np.random.randint(0,100,(3,3))

array([[13, 19, 99],
       [85, 16, 88],
       [36, 13, 94]])

In [20]:
np.random.seed(101) 
np.random.randint(0,1000,10)

array([863, 523, 337, 838, 575, 599,  75, 393, 973, 552])

In [21]:
np.random.randint(0,1000,10)

array([644, 575, 936, 757, 316, 732, 704, 110,   5, 908])

In [28]:
np.random.seed(101)
arr = np.random.randint(0,1000,10)
np.random.randint(0,1000,10)

array([644, 575, 936, 757, 316, 732, 704, 110,   5, 908])

In [29]:
arr.max()

973

In [30]:
arr.argmax()

8

In [31]:
arr.reshape(2,5)

array([[863, 523, 337, 838, 575],
       [599,  75, 393, 973, 552]])

In [37]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
## looking for 96
mat[9,6]

96

In [40]:
## looking for all rows in column 4 
mat[:,4]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [41]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [44]:
## Masking 
my_filter = mat > 50
mat[my_filter] 
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])