In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [10]:
data = np.random.randint(0.,100,(10,2))
data

array([[36,  9],
       [42, 68],
       [ 1,  1],
       [60, 33],
       [56, 94],
       [29, 27],
       [40,  7],
       [74, 78],
       [84, 95],
       [76, 31]])

In [11]:
scaler_model = MinMaxScaler()

In [12]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [13]:
scaler_model.fit(data)

C:\Users\AndrewTran\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [14]:
scaler_model.transform(data)

array([[ 0.42168675,  0.08510638],
       [ 0.4939759 ,  0.71276596],
       [ 0.        ,  0.        ],
       [ 0.71084337,  0.34042553],
       [ 0.6626506 ,  0.9893617 ],
       [ 0.3373494 ,  0.27659574],
       [ 0.46987952,  0.06382979],
       [ 0.87951807,  0.81914894],
       [ 1.        ,  1.        ],
       [ 0.90361446,  0.31914894]])

In [15]:
scaler_model.fit_transform(data)

C:\Users\AndrewTran\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


array([[ 0.42168675,  0.08510638],
       [ 0.4939759 ,  0.71276596],
       [ 0.        ,  0.        ],
       [ 0.71084337,  0.34042553],
       [ 0.6626506 ,  0.9893617 ],
       [ 0.3373494 ,  0.27659574],
       [ 0.46987952,  0.06382979],
       [ 0.87951807,  0.81914894],
       [ 1.        ,  1.        ],
       [ 0.90361446,  0.31914894]])

In [21]:
import pandas as pd
df = pd.DataFrame(data = np.random.randint(0,101,(50,4)), columns = ['f1','f2','f3','label'])

In [23]:
df

f1   f2  f3  label
0   36   59  96     60
1    3   90  66     72
2   45   37  92     44
3   95   97  36     14
4   17  100  23     29
5   73   96  95     61
6   95   98  13     72
7   50   84  57     41
8   85   47  35      6
9   15    2  85      4
10  17   52  75     34
11  36   88  30     94
12  43   10  43     73
13  70   87  40     85
14  19   35   1     50
15  56   84  24     37
16  24   75  69     58
17  52   75  79     36
18   8   36  19     59
19  18   43  73     81
20  36   29   0      0
21  35   57  78     62
22  32   69  17     12
23   3   15  15     54
24  47  100  75     24
25  28   57  81     59
26   7  100  78     93
27  42   57  17     12
28  94   21  44     36
29  10   70  25     91
30  94   70   3     57
31  73   22   3     98
32  59   36  94     27
33  39   67  51     67
34   4   99  25     16
35  44   85  52      7
36  53   95  39     16
37  67    8  55     34
38   4   51  34     88
39  60   69  21     32
40  92   31  38     68
41  17   54  33     32
42  36   29   6     32
43  37   23  31     61
44  58   37  60     87
45   1   40  56     93
46  36    8  18     83
47   9   19  91     39
48  61   87  91     63
49  52   66  61     59

In [25]:
X = df[['f1','f2','f3']]
X

f1   f2  f3
0   36   59  96
1    3   90  66
2   45   37  92
3   95   97  36
4   17  100  23
5   73   96  95
6   95   98  13
7   50   84  57
8   85   47  35
9   15    2  85
10  17   52  75
11  36   88  30
12  43   10  43
13  70   87  40
14  19   35   1
15  56   84  24
16  24   75  69
17  52   75  79
18   8   36  19
19  18   43  73
20  36   29   0
21  35   57  78
22  32   69  17
23   3   15  15
24  47  100  75
25  28   57  81
26   7  100  78
27  42   57  17
28  94   21  44
29  10   70  25
30  94   70   3
31  73   22   3
32  59   36  94
33  39   67  51
34   4   99  25
35  44   85  52
36  53   95  39
37  67    8  55
38   4   51  34
39  60   69  21
40  92   31  38
41  17   54  33
42  36   29   6
43  37   23  31
44  58   37  60
45   1   40  56
46  36    8  18
47   9   19  91
48  61   87  91
49  52   66  61

In [26]:
Y = df['label']

In [27]:
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,Y_train,Y_test = train_test_split(X, Y, test_size = 0.3,random_state = 100)

In [30]:
X_train.shape

(35, 3)

In [31]:
X_test.shape

(15, 3)